apiVersion: apps/v1
kind: Deployment
metadata:
  name: SatisfactionManagement
  labels:
    app: SatisfactionManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SatisfactionManagement
  template:
    metadata:
      labels:
        app: SatisfactionManagement
    spec:
      containers:
        - name: SatisfactionManagement
          image: username/SatisfactionManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5