apiVersion: v1
kind: Service
metadata:
  name: SatisfactionManagement
  labels:
    app: SatisfactionManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SatisfactionManagement